from __future__ import annotations
from sensorthings import defaults as ST

ALLOWED_HOSTS = ["*"]

DATABASES = {"default": ST.DATABASE_OPTIONS["spatialite"]}

INSTALLED_APPS = [*ST.INSTALLED_APPS]

ROOT_URLCONF = "tests.urls"

TEMPLATES = [{"BACKEND": "django.template.backends.django.DjangoTemplates"}]

SECRET_KEY = "DEMOTESTSECRET"

SECURE_PROXY_SSL_HEADER = ("HTTP_FAKE_SECURE", "true")

USE_TZ = True

REST_FRAMEWORK = ST.REST_FRAMEWORK
SIMPLE_JWT = ST.SIMPLE_JWT
SPECTACULAR_SETTINGS = ST.SPECTACULAR_SETTINGS
SWAGGER_SETTINGS = ST.SWAGGER_SETTINGS
SENSORTHINGS_ENABLE_PUBLIC_PRIVATE = ST.SENSORTHINGS_ENABLE_PUBLIC_PRIVATE
SENSORTHINGS_ENABLE_OWNER = ST.SENSORTHINGS_ENABLE_OWNER
