name: CI

on:
  push:
    branches:
    - development/prepare
    # tags:
    # - '**'
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    strategy:
      matrix:
        python-version:
        - '3.12'
        # - '3.13'
        # - '3.14'

    steps:
    - uses: actions/checkout@v6

    - name: Install GDAL and geospatial libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev libgeos-dev libproj-dev

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Write lock file
      run: uv sync


    - name: Run tox targets for ${{ matrix.python-version }}
      run: uvx --with tox-uv tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)

    - name: Upload coverage data
      uses: actions/upload-artifact@v7
      with:
        name: coverage-data-${{ matrix.python-version }}
        path: '${{ github.workspace }}/.coverage/*'
        include-hidden-files: true
        if-no-files-found: error

    
    - name: Result of build
      run: |
        ls 
        echo "#####"
        uv build 
        echo "#####"
        ls 
        echo "#####"
        ls dist
  
    - name: Commit lock file
      uses: ./.github/actions/commit-and-push
      with:
        commit-message: "chore: update lock file"